version: '3.8'
services:
  server:
    image: 'url-shortener-server:latest'
    build:
      context: "."
      dockerfile: Dockerfile-server
    container_name: url-shortener-server
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/url_shortener_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
    links:
      - "postgres:database"
    ports:
      - 8080:8080

  client:
    image: 'url-shortener-client:latest'
    build:
      context: "."
      dockerfile: Dockerfile-client
    container_name: url-shortener-client
    depends_on:
      - server
    ports:
      - 8088:8088

  postgres:
    image: 'postgres:13.2-alpine'
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=url_shortener_db
    ports:
      - 5433:5432