FROM node:14.16.1-alpine as builder

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY src/main/webapp/package.json ./
COPY src/main/webapp/yarn.lock ./
COPY src/main/webapp/ ./

RUN yarn install
RUN yarn build

# Static serve
RUN yarn global add serve
CMD ["serve", "-s", "build", "-l", "8088"]

# Server runs with nginx
# FROM nginx:alpine
# RUN rm -rf /etc/nginx/conf.d
# COPY nginx-conf /etc/nginx
# COPY --from=builder /app/build /usr/share/nginx/html
# EXPOSE 8088
# CMD ["nginx", "-g", "daemon off;"]

